### ISSUE TITLE
loss problem

### ISSUE THREAD

**Issue by ximi1211** [InhwanBae/GPGraph#2] opened 2022-08-27 02:26 UTC
Hello, may I ask why my loss is always 0 since the first epoch?
![image](https://user-images.githubusercontent.com/80146128/187010655-0668c898-6860-4b47-9ec2-46b3aa47be70.png)
![image](https://user-images.githubusercontent.com/80146128/187010679-f4e889ef-2228-44ca-a3e1-554af86766b4.png)

**Comment by InhwanBae** [comment] 2022-08-27 16:22
Hi @ximi1211!

Thank you for letting me know about this issue. In the last few hours, I've analyzed the cause of this problem. Finally, I figured out that one line of code that I rewrote to clean up before public release caused a problem. The equation is the same, but I still don't know why *nan* appears during back-propagation (I replaced the loss with *0* if its value is *nan*). Please **replace the 59th line** in [`model_groupwrapper.py`](https://github.com/InhwanBae/GPGraph/blob/main/model_groupwrapper.py#L59) with the PyTorch built-in function as follows:

```python
# sig = 1 / (1 + ((dist_mat - self.th) / tau).exp())
sig = (-(dist_mat - self.th) / tau).sigmoid()
```

**Comment by InhwanBae** [comment] 2022-09-06 01:28
I'm closing this issue for now. Please feel free to open another issue for other questions.

**Closed as completed by InhwanBae** 2022-09-06 01:28 UTC
